import java.util.Random;

public class exp {
    public static void main(String[] args) {
        static void nesttry(int a) {
        try { // nested try block
/* If one command-line arg is used,
then a divide-by-zero exception
will be generated by the following code. */
            if(a==1) a = a/(a-a); // division by zero
/* If two command-line args are used,
then generate an out-of-bounds exception. */
            if(a==2) {
                int c[] = { 1 };
                c[42] = 99; // generate an out-of-bounds exception
            }
        } catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("Array index out-of-bounds: " + e);
        }
    }
    public static void main(String args[]) {
        try {
            int a = args.length;
/* If no command-line args are present,
the following statement will generate
a divide-by-zero exception. */
            int b = 42 / a;
            System.out.println("a = " + a);
            nesttry(a);
        } catch(ArithmeticException e) {
            System.out.println("Divide by 0: " + e);
        }}}}






/* double a,b;
        try{
            a=0;
            b=21/a;//ager yahn divid by 0 ka error hoga to divid error print hoga
            System.out.println(b);//ager 0 ka error nai hoga to this will not be printed
            System.out.println("this will not be printed");
        }catch (ArithmeticException e){
            System.out.println("division error:");
        }*/
/* int a=0 ,b=0,c=0;
           Random r = new Random();

             for (int i = 0; i <=3200; ) {
    try {
        b = r.nextInt();
        c = r.nextInt();
        a = 12345 / (b / c);
    } catch (ArithmeticException e) {
        System.out.printf("division by zero.");
        a = 9;
        //a=12345/(b/c);ager yahn ye lihunga to division by zero print hoga
    }
    System.out.println("a:" + b);
}}}*/
/* try{
            int a=1;//ageryahn 0 dunga to catch or ausky statment ko runn karega
            //or 1 duga to out f bound lekin array 42 hona zarori ha
            //or ager 42 zada ha to bi out of bond hoga
            System.out.println("a="+a);
            int b=42/a;
            int c[]={1};
            c[42]=42;

        }catch(ArithmeticException e){
            System.out.println("divide by zero"+e);
        }
        System.out.println("after try /catch blocks.");
    }}*/
//------------------------/
/*try {
            int a = args.length;
/* If no command-line args are present,
the following statement will generate
a divide-by-zero exception. */
/*int b = 42 / a;
            System.out.println("a = " + a);
                    try { // nested try block
/* If one command-line arg is used,
then a divide-by-zero exception
will be generated by the following code. */
                    // if(a==1) a = a/(a +a); // division by zero
/* If two command-line args are used,
then generate an out-of-bounds exception. */
/*                    if(a==2) {
                    int c[] = { 1 };
                    c[42] = 99; // generate an out-of-bounds exception
                    }
                    } catch(ArrayIndexOutOfBoundsException e) {
                    System.out.println("Array index out-of-bounds: " + e);
                    }
                    } catch(ArithmeticException e) {
                    System.out.println("Divide by 0: " + e);
                    }}}
                    */
